trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.5.0'
  TF_WORKING_DIR: './'

steps:
- task: UseTerraform@0
  inputs:
    version: '$(TF_VERSION)'

- script: |
    cd $(TF_WORKING_DIR)
    terraform init
    terraform fmt -check
    terraform validate
    terraform plan -out=tfplan.out
  displayName: 'Terraform Init, Fmt, Validate, Plan'

- script: |
    cd $(TF_WORKING_DIR)
    terraform apply -auto-approve tfplan.out
  displayName: 'Terraform Apply'
